package client

import "fmt"

// GraphQLCallError is a root level error struct generated by grafik.
// It corresponds to GraphQL HTTP error response as per specification: http://spec.graphql.org/October2021/#sec-Errors.Error-result-format
type GraphQLCallError struct {
	Message string
	Reason  string
}

func (e GraphQLCallError) Error() string {
	return fmt.Sprintf("GraphQL call failed. Message=%s Reason=%s", e.Message, e.Reason)
}
