package generator

import (
	"fmt"
	"github.com/Bartosz-D3V/grafik/common"
	"strings"
)

type TypeArg struct {
	Name string
	Type string
}

// ExportName converts name of the argument to Title case.
func (t TypeArg) ExportName() string {
	return strings.Title(t.Name)
}

// ExportType converts argument type to Title case excluding golang primitive types.
func (t TypeArg) ExportType() TypeArg {
	const sliceTok = "[]"
	if strings.Contains(t.Type, sliceTok) {
		dim := strings.Count(t.Type, sliceTok)
		elType := strings.TrimLeft(t.Type, sliceTok)
		if isPrimitive(elType) {
			return t
		}
		return TypeArg{
			Name: t.Name,
			Type: fmt.Sprintf("%s%s", strings.Repeat(sliceTok, dim), strings.Title(elType)),
		}
	}
	if isPrimitive(t.Type) {
		return t
	}
	return TypeArg{
		Name: t.Name,
		Type: strings.Title(t.Type),
	}
}

// PointerType converts TypeArg to pointer type, excluding arrays/slices.
func (t TypeArg) PointerType() TypeArg {
	if strings.Contains(t.Type, "[]") {
		return t
	}
	return TypeArg{
		Name: t.Name,
		Type: fmt.Sprintf("*%s", t.Type),
	}
}

// isPrimitive checks if passed golang type is primitive.
// It only checks golang primitives generated by evaluator.
func isPrimitive(s string) bool {
	return s == "string" || s == "int" || s == "bool"
}

type Func struct {
	Name        string
	Args        []TypeArg
	Type        string
	WrapperArgs []TypeArg
}

// JoinArgsBy returns list of function arguments as concatenated string with name and type.
func (f Func) JoinArgsBy(s string) string {
	pArgs := make([]string, len(f.Args))
	for i, arg := range f.Args {
		tArg := arg.ExportType()
		pArgs[i] = fmt.Sprintf("%s %s", tArg.Name, common.SnakeCaseToCamelCase(tArg.Type))
	}

	return strings.Join(pArgs, s)
}

// ExportName converts name of the function to Title case.
func (f Func) ExportName() string {
	return strings.Title(f.Name)
}

type Struct struct {
	Name   string
	Fields []TypeArg
}

type Enum struct {
	Name   string
	Fields []string
}

type Const struct {
	Name string
	Val  interface{}
}

// IsString returns true if passed interface{} is a string.
func (c Const) IsString() bool {
	switch c.Val.(type) {
	case string:
		return true
	default:
		return false
	}
}
