run:
  timeout: 5m
linters:
  enable:
    - cyclop
    - depguard
    - dupl
    - errname
    - exhaustive
    - gochecknoglobals
    - gocognit
    - goconst
    - godot
    - gomnd
    - gosec
    - ifshort
    - importas
    - misspell
    - gocritic
    - unconvert
    - unparam
    - wastedassign
    - nestif
    - prealloc
    - paralleltest
    - noctx
    - deadcode
    - revive
    - whitespace
    - gofmt
    - nilerr
    - exportloopref
    - asciicheck
linters-settings:
  godot:
    exclude:
      - '[}]+'
  cyclop:
    max-complexity: 11
